import React from 'react'
import '~/styles/globals.css'
import '@uploadthing/react/styles.css'
import { ClerkProvider } from '@clerk/nextjs'
import { GeistSans } from 'geist/font/sans'
import TopNav from '~/_components/topnav'
import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin'
import { extractRouterConfig } from 'uploadthing/server'
import { ourFileRouter } from '~/app/api/uploadthing/core'
import { ThemeProvider } from '~/_components/ThemeProvider/ThemeProvider'

export const metadata = {
    title: 'Salary Gallery',
    description: 'Generated by create-t3-app',
    icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({
    children,
    modal,
}: {
    children: React.ReactNode
    modal?: React.ReactNode
}) {
    return (
        <ClerkProvider>
            {/*<html lang="en" className={`${GeistSans.variable} flex flex-col gap-4 bg-[url('/background.avif')]`}>*/}
            <html
                lang="en"
                className={`${GeistSans.variable} flex flex-col gap-4`}
            >
                <NextSSRPlugin
                    routerConfig={extractRouterConfig(ourFileRouter)}
                />

                <body>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <div className="h-screen grid grid-rows-[auto,1fr]">
                            <TopNav />
                            <main className="overflow-y-scroll">
                                {children}
                            </main>
                        </div>
                        {modal}
                        <div id="modal-root" />
                    </ThemeProvider>
                </body>
            </html>
        </ClerkProvider>
    )
}
