import '~/styles/globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { GeistSans } from 'geist/font/sans'
import TopNav from '~/components/topnav'
import React from 'react'


export const metadata = {
    title: 'Salary Gallery',
    description: 'Generated by create-t3-app',
    icons: [{ rel: 'icon', url: '/favicon.ico' }],
}


export default function RootLayout({ children }: {
    children: React.ReactNode;
}) {
    return (
        <ClerkProvider>
            <html lang="en" className={`${GeistSans.variable} flex flex-col gap-4`}>
            <body>
            <TopNav />
            {children}
            </body>
            </html>
        </ClerkProvider>

    )
}
